# -*- coding: utf-8 -*-
"""H01_16520002_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X6l-Rb_xqALwwMfY-v8iywH-PnvFByai
"""

print("Hello, World!")