# -*- coding: utf-8 -*-
"""H01_16520002_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cFFrpbl7IVkN7xWg3OqaZrhXhkwJynlO
"""

# Eraraya Morenzo Muten
# 16520002
# Program Problem 2: Kalkulator sederhana 2 buah angka

# KAMUS
#  a1: int
#  a2: int
#  op: str
#  hs: int

#ALGORITMA
a1 = int(input("Masukkan angka pertama : "))                  #assign variabel a1 sebagai input angka pertama
a2 = int(input("Masukkan angka kedua : "))                    #assign variabel a2 sebagai input angka kedua
op = input("Masukkan operator : ")                            #assign variabel op sebagai input operator

if op == "+":                                                 #jika operator tambah
  hs = a1 + a2                                                #assign variabel hs sebagai penjumlahan a1 dengan a2

elif op == "-":                                               #jika operator kurang
  hs = a1 - a2                                                #assign variabel hs sebagai pengurangan a1 dengan a2

elif op == "*":                                               #jika operator kali
  hs = a1 * a2                                                #assign variabel hs sebagai perkalian a1 dengan a2

elif op == "/":                                               #jika operator bagi, dibulatkan ke bawah
  hs = a1 // a2                                               #assign variabel hs sebagai pembagian a1 dengan a2 kemudian dibulatkan ke bawah

elif op == "%":                                               #jika operator sisa bagi
  hs = a1 % a2                                                #assign variabel hs sebagai sisa dari pembagian a1 dengan a2

print(str(a1) + " " + op + " " + str(a2) + " = " + str(hs))   #menampilkan hasil