# -*- coding: utf-8 -*-
"""H01_16520002_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EWYHLmzMqKFZgX8Iiw4wHSXmrtkfhlb_
"""

# Eraraya Morenzo Muten
# 16520002
# Program Problem 3: Penggolongan sifat paritas dan tanda satu bilangan

# KAMUS
#  X: int

#ALGORITMA
X = int(input("Masukkan X: "))                  #assign variabel X sebagai input angka

if X == 0:                                      #jika X sama dengan 0
  print("X adalah bilangan nol")                #menampilkan golongan X

elif X < 0:                                     #jika X kurang dari 0
  print("X adalah bilangan negatif")            #menampilkan tanda X

elif X > 0:                                     #jika X lebih dari 0
  if X % 2 == 0:                                #jika X bilangan genap
    print("X adalah bilangan positif genap")    #menampilkan tanda dan paritas X

  elif X % 2 == 1:                              #jika X bilangan ganjil
    print("X adalah bilangan positif ganjil")   #menampilkan tanda dan paritas X